version: '2'
services:

  # Redis cluster needed for STREAM events (Single node, development only)
  redis:
    image: 'redis:6.0'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - ./conf/redis01:/opt/redis-conf
      - ./data/redis01:/data
    ports:
      - '6379:6379'

  # Simple Example application with HAProxy load balancer (Development only)
  # WARNING: local filesystem is mounted into docker image to help development and debugging
  # for production use `make dist`, copy and install engine and apps with pip from DockerFile.
  simple-example:
    build: engine
    volumes:
      - ./engine/config/haproxy.cfg:/etc/haproxy/haproxy.cfg
      - ./engine/config/supervisord.conf:/etc/supervisord.conf
      - ./engine/config/bootstrap.sh:/opt/hopeit.engine/bootstrap.sh
      - ../engine:/opt/hopeit.engine/engine
      - ../apps:/opt/hopeit.engine/apps
      - ../plugins:/opt/hopeit.engine/plugins
    ports:
      - '80:80'
      - '443:443'
