filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

output.logstash:
  hosts: ['${LOGSTASH_HOST:logstash}:${LOGSTASH_PORT:5044}']

filebeat.inputs:
- type: log
  paths:
    - "/logs/hopeit/apps/*.log*"
