# This workflow will make hopeit.engine package and deploy on PyPI

name: hopeit.engine Test PyPI Publishing

on:
  release:
    types: [unpublished, prereleased]

jobs:
  upload:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
    
    - name: install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
    
    - name: make ci-deps
      run: PYTHONVERSION=${{ matrix.python-version }} make ci-deps

    - name: make dist-engine
      run: |
        make dist-engine

    - name: make dist-plugin redis_streams
      run: |
        make PLUGINFOLDER=plugins/streams/redis/ dist-plugin

    - name: publish engine on Test PyPI
      env: 
        TEST_PYPI_API_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN_ALL }}
      run: |
        make publish-engine-pypi-test

    - name: publish redis_streams on Test PyPI
      env: 
        TEST_PYPI_API_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN_ALL }}
      run: |
        make PLUGINFOLDER=plugins/streams/redis publish-plugins-pypi-test
