# This workflow will make hopeit.engine package and deploy on PyPI

name: hopeit.engine PyPI Publishing

on:
  release:
    types: [published]

jobs:
  upload:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Build and publish Python 🐍 distributions 📦 to PyPI
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        make locked-deps
    - name: QA
      run: |
        make qa

    - name: make hopeit.engine package
      run: |
        make dist
    - name: make plugin redis-streams
      run: |
        make PLUGINFOLDER=plugins/streams/redis/ dist-plugin
    - name: make plugin redis-storage
      run: |
        make PLUGINFOLDER=plugins/storage/redis/ dist-plugin
    - name: make plugin fs-storage
      run: |
        make PLUGINFOLDER=plugins/storage/fs/ dist-plugin
    - name: make plugin config-manager
      run: |
        make PLUGINFOLDER=plugins/ops/config-manager/ dist-plugin
    - name: make plugin log-streamer
      run: |
        make PLUGINFOLDER=plugins/ops/log-streamer/ dist-plugin
    - name: make plugin apps-visualizer
      run: |
        make PLUGINFOLDER=plugins/ops/apps-visualizer/ dist-plugin
    - name: make plugin apps-client
      run: |
        make PLUGINFOLDER=plugins/clients/apps-client/ dist-plugin
    - name: make plugin dataframes
      run: |
        make PLUGINFOLDER=plugins/data/dataframes/ dist-plugin

    - name: Publish hopeit.engine on PyPI
      env: 
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        make pypi
    - name: Publish plugin redis-streams on PyPI
      env: 
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        make PLUGINFOLDER=plugins/streams/redis pypi-plugin
    - name: Publish plugin redis-storage on PyPI
      env: 
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        make PLUGINFOLDER=plugins/storage/redis pypi-plugin        
    - name: Publish plugin fs-storage on PyPI
      env: 
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        make PLUGINFOLDER=plugins/storage/fs pypi-plugin
    - name: Publish plugin config-manager on PyPI
      env: 
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        make PLUGINFOLDER=plugins/ops/config-manager pypi-plugin
    - name: Publish plugin log-streamer on PyPI
      env: 
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        make PLUGINFOLDER=plugins/ops/log-streamer pypi-plugin
    - name: Publish plugin apps-visualizer on PyPI
      env: 
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        make PLUGINFOLDER=plugins/ops/apps-visualizer pypi-plugin
    - name: Publish plugin apps-client on PyPI
      env: 
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        make PLUGINFOLDER=plugins/clients/apps-client pypi-plugin
    - name: Publish plugin dataframes on PyPI
      env: 
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        make PLUGINFOLDER=plugins/data/dataframes pypi-plugin